{
 "title": "Vault Cluster A - NYC",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": "show tag values on telegraf from cpu with key = \"host\" where role = 'vault-ent-cluster-a_node-1'"
   },
   {
    "name": "dc",
    "label": "Datacenter",
    "query": "show tag values on telegraf from cpu with key = \"datacenter\" where role = 'vault-ent-cluster-a_node-1'"
   }
  ]
 },
 "panels": [
  {
   "title": "Request Handle Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms", "label": "Time" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "vault.core.handle_request",
     "query": "SELECT mean(\"value\") AS \"count\" FROM \"telegraf\".\"autogen\".\"vault.core.handle_request\" WHERE $timeFilter AND \"role\"='consul-vault-ent-cluster-a_node-1' GROUP BY time($__interval), \"host\" FILL(null)",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "datacenter", "operator": "=~", "value": "/^primary/" }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT max(\"usage_user\") AS \"user_cpu\", max(\"usage_iowait\") AS \"iowait_cpu\" FROM \"telegraf\".\"autogen\".\"cpu\" WHERE (\"role\" = 'vault-ent-cluster-a_node-1' AND \"host\" =~ /^$host$/ AND \"datacenter\" =~ /^primary/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "role", "operator": "=", "value": "vault-ent-cluster-a_node-1" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "datacenter", "operator": "=~", "value": "/^primary/" }
     ]
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 7 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "query": "SELECT non_negative_difference(max(\"read_bytes\")) + non_negative_difference(max(\"write_bytes\")) AS \"bytes\" FROM \"telegraf\".\"autogen\".\"diskio\" WHERE (\"role\" = 'vault-ent-cluster-a_node-1' AND \"host\" =~ /^$host$/ AND \"datacenter\"  =~ /^primary/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "read_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      {
       "key": "role",
       "operator": "=",
       "value": "consul-vault-ent-cluster-a_node-1"
      }
     ]
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 7 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "SELECT non_negative_difference(max(\"bytes_recv\")) + non_negative_difference(max(\"bytes_sent\")) AS \"bytes\" FROM \"telegraf\".\"autogen\".\"net\" WHERE (\"role\" = 'vault-ent-cluster-a_node-1' AND \"host\" =~ /^$host$/ AND \"datacenter\" =~ /^primary/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      {
       "key": "role",
       "operator": "=",
       "value": "consul-vault-ent-cluster-a_node-1"
      }
     ]
    }
   ]
  },
  {
   "title": "GC Pause Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 15, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "vault.runtime.gc_pause_ns",
     "query": "SELECT last(\"upper\")/1000000 AS \"milliseconds\" FROM \"telegraf\".\"autogen\".\"vault.runtime.gc_pause_ns\" WHERE $timeFilter AND \"role\"='vault-ent-cluster-a_node-1' GROUP BY host, time($__interval) FILL(0)",
     "select": [
      [
       { "params": [ "upper" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "role", "operator": "=", "value": "vault-ent-cluster-a_node-1" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "datacenter", "operator": "=~", "value": "/^primary/" }
     ]
    }
   ]
  },
  {
   "title": "Runtime Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 19, "y": 7 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "vault.runtime.alloc_bytes",
     "query": "SELECT max(\"value\") AS \"alloc_bytes\" FROM \"telegraf\".\"autogen\".\"vault.runtime.alloc_bytes\" WHERE (\"role\" = 'vault-ent-cluster-a_node-1' AND \"host\" =~ /^$host$/ AND \"datacenter\" =~ /^primary/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "role", "operator": "=", "value": "vault-ent-cluster-a_node-1" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"value\") AS \"sys_bytes\" FROM \"telegraf\".\"autogen\".\"vault.runtime.sys_bytes\" WHERE (\"role\" = 'vault-ent-cluster-a_node-1' AND \"host\" =~ /^$host$/ AND \"datacenter\" =~ /^primary/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "query": "SELECT mean(\"total\") AS \"total_bytes\" FROM \"telegraf\".\"autogen\".\"mem\" WHERE (\"host\" =~ /^$host$/ AND \"datacenter\" =~ /^primary/ AND \"role\" = 'vault-ent-cluster-a_node-1') AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "datacenter", "operator": "=~", "value": "/^primary/" },
      { "condition": "AND", "key": "role", "operator": "=", "value": "vault-ent-cluster-a_node-1" }
     ]
    }
   ]
  },
  {
   "title": "WAL Persist Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "vault.wal.persistWALs",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "datacenter", "operator": "=~", "value": "/^primary/" }
     ]
    }
   ]
  },
  {
   "title": "WAL Flush Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 9, "y": 13 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "vault.wal.flushReady",
     "select": [
      [
       { "params": [ "upper" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "datacenter", "operator": "=~", "value": "/^primary/" }
     ]
    }
   ]
  },
  {
   "title": "Leadership Loss",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 17, "y": 13 },
   "format": "ms",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "vault.core.leadership_lost",
     "query": "SELECT max(\"upper\") FROM \"telegraf\".\"autogen\".\"vault.core.leadership_lost\" WHERE (\"datacenter\" =~ /^primary/) AND $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Seal Status",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 6, "x": 17, "y": 17 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "service_name" ], "type": "tag" }
     ],
     "measurement": "consul_health_checks",
     "query": "SELECT last(\"passing\") AS unsealed FROM \"telegraf\".\"autogen\".\"consul_health_checks\" WHERE role='vault-ent-cluster-a_node-1' AND check_name='Vault Sealed Status' GROUP BY \"check_id\"",
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  }
 ]
}