# StorageClass.yml

apiVersion: secrets-store.csi.k8s.com/v1alpha1
kind: SecretProviderClass
metadata:
  name: vault-foo
spec:
  provider: vault
  parameters:
    roleName: "example-role"
    vaultAddress: "http://10.96.122.78:8200"
    vaultSkipTLSVerify: "true"
    objects:  |
      array:
        - |
          objectPath: "/foo"
          objectName: "bar"
          objectVersion: ""