variable "aws_region" {
  type        = string
  description = "Name of AWS region to place resources"
}

variable "vpc_id" {
  type        = string
  description = "The VPC ID to place resources"
}

variable "immutable_vault_raft_ami_id" {
  type = string
  description = "Machine image ID generated by Packer build of is-vault-amzn2.json"
}

variable "vault_domain" {
  type = string
}
